### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [jessiefascal87/prj-rev-bwfs-dasmoto#6]
https://github.com/jessiefascal87/prj-rev-bwfs-dasmoto/blob/master/DasmotosArt/style.css#L24-L50

There's a lot of repetition in your CSS. Move shared styles into a more general selector so that those styles only need to be applied in one place and can be removed from the others.

```css
h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```

(By the way, if you'd given each `div` tag a class of "product", you could write the selector `.product h2` which reads a lot more descriptively than just `h2` or listing the different IDs).

You're also repeating the `font-family` style in a lot of these CSS rules, and in some CSS rules it's the only style being applied.

Consider applying this style in a more general selector, like `*`, so that you can just apply it to everything by default and write less code in the process.

```css
* {
  font-family: Helvetica;
}
```
